### ISSUE TITLE
model_form(only) broken in python3

### ISSUE THREAD

**Issue by ak64th** [MongoEngine/flask-mongoengine#110]
class User(Document, UserMixin):
        email = EmailField(unique=True)
        password = StringField(default=True)
        active = BooleanField(default=True)
        isAdmin = BooleanField(default=False)
        timestamp = DateTimeField(default=datetime.datetime.now())

    UserForm = model_form(User,only=['email','password'])
    UserForm.password

The code works in python2.7 but throw an AttributeError in python3.4

    AttributeError: type object 'UserForm' has no attribute 'password'

**Comment by icoz** [comment]
Workaround is change orm.py:233 to     
field_names = [x for x in map(itemgetter(0), sorted(names, key=itemgetter(1)))]

**Comment by lafrech** [comment]
Should this issue be closed?

**Comment by icoz** [comment]
I think yes.
6 февр. 2016 г. 17:31 пользователь "Jérôme Lafréchoux" <
notifications@github.com> написал:

**Comment by ak64th** [comment]
Yes it's fixed. Thank you.
